// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: dns/dns.proto

package dns

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DNSServiceClient is the client API for DNSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DNSServiceClient interface {
	SetHostname(ctx context.Context, in *SetHostnameRequest, opts ...grpc.CallOption) (*SetHostnameResponse, error)
	GetDNS(ctx context.Context, in *GetDNSRequest, opts ...grpc.CallOption) (*GetDNSResponse, error)
	AddDNS(ctx context.Context, in *AddDNSRequest, opts ...grpc.CallOption) (*AddDNSResponse, error)
	RemoveDNS(ctx context.Context, in *RemoveDNSRequest, opts ...grpc.CallOption) (*RemoveDNSResponse, error)
}

type dNSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDNSServiceClient(cc grpc.ClientConnInterface) DNSServiceClient {
	return &dNSServiceClient{cc}
}

func (c *dNSServiceClient) SetHostname(ctx context.Context, in *SetHostnameRequest, opts ...grpc.CallOption) (*SetHostnameResponse, error) {
	out := new(SetHostnameResponse)
	err := c.cc.Invoke(ctx, "/dns.DNSService/SetHostname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSServiceClient) GetDNS(ctx context.Context, in *GetDNSRequest, opts ...grpc.CallOption) (*GetDNSResponse, error) {
	out := new(GetDNSResponse)
	err := c.cc.Invoke(ctx, "/dns.DNSService/GetDNS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSServiceClient) AddDNS(ctx context.Context, in *AddDNSRequest, opts ...grpc.CallOption) (*AddDNSResponse, error) {
	out := new(AddDNSResponse)
	err := c.cc.Invoke(ctx, "/dns.DNSService/AddDNS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSServiceClient) RemoveDNS(ctx context.Context, in *RemoveDNSRequest, opts ...grpc.CallOption) (*RemoveDNSResponse, error) {
	out := new(RemoveDNSResponse)
	err := c.cc.Invoke(ctx, "/dns.DNSService/RemoveDNS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DNSServiceServer is the server API for DNSService service.
// All implementations must embed UnimplementedDNSServiceServer
// for forward compatibility
type DNSServiceServer interface {
	SetHostname(context.Context, *SetHostnameRequest) (*SetHostnameResponse, error)
	GetDNS(context.Context, *GetDNSRequest) (*GetDNSResponse, error)
	AddDNS(context.Context, *AddDNSRequest) (*AddDNSResponse, error)
	RemoveDNS(context.Context, *RemoveDNSRequest) (*RemoveDNSResponse, error)
	mustEmbedUnimplementedDNSServiceServer()
}

// UnimplementedDNSServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDNSServiceServer struct {
}

func (UnimplementedDNSServiceServer) SetHostname(context.Context, *SetHostnameRequest) (*SetHostnameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHostname not implemented")
}
func (UnimplementedDNSServiceServer) GetDNS(context.Context, *GetDNSRequest) (*GetDNSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDNS not implemented")
}
func (UnimplementedDNSServiceServer) AddDNS(context.Context, *AddDNSRequest) (*AddDNSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDNS not implemented")
}
func (UnimplementedDNSServiceServer) RemoveDNS(context.Context, *RemoveDNSRequest) (*RemoveDNSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDNS not implemented")
}
func (UnimplementedDNSServiceServer) mustEmbedUnimplementedDNSServiceServer() {}

// UnsafeDNSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DNSServiceServer will
// result in compilation errors.
type UnsafeDNSServiceServer interface {
	mustEmbedUnimplementedDNSServiceServer()
}

func RegisterDNSServiceServer(s grpc.ServiceRegistrar, srv DNSServiceServer) {
	s.RegisterService(&DNSService_ServiceDesc, srv)
}

func _DNSService_SetHostname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHostnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSServiceServer).SetHostname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dns.DNSService/SetHostname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSServiceServer).SetHostname(ctx, req.(*SetHostnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSService_GetDNS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDNSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSServiceServer).GetDNS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dns.DNSService/GetDNS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSServiceServer).GetDNS(ctx, req.(*GetDNSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSService_AddDNS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDNSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSServiceServer).AddDNS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dns.DNSService/AddDNS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSServiceServer).AddDNS(ctx, req.(*AddDNSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSService_RemoveDNS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDNSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSServiceServer).RemoveDNS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dns.DNSService/RemoveDNS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSServiceServer).RemoveDNS(ctx, req.(*RemoveDNSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DNSService_ServiceDesc is the grpc.ServiceDesc for DNSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DNSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dns.DNSService",
	HandlerType: (*DNSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetHostname",
			Handler:    _DNSService_SetHostname_Handler,
		},
		{
			MethodName: "GetDNS",
			Handler:    _DNSService_GetDNS_Handler,
		},
		{
			MethodName: "AddDNS",
			Handler:    _DNSService_AddDNS_Handler,
		},
		{
			MethodName: "RemoveDNS",
			Handler:    _DNSService_RemoveDNS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dns/dns.proto",
}
